site_name: FastUMI Go 使用手册
site_url: https://lee82683049595030-ctrl.github.io/
nav:
  - 欢迎页: README.md
  - FastUMI Go 使用手册: FastUMI Go使用手册.md
theme:
  name: material
  language: zh-CN
  highlightjs: true
plugins:
  - search
